spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    password: sa
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        format_sql: 'true'
    show-sql: 'true'
  h2:
    console:
      path: /h2-console
      enable: 'true'